version: '3.8'

services:
  spectrum-prism:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prism
    volumes:
      - .:/app
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=spectrum
      - TIINGO_API_KEY=${TIINGO_API_KEY}
    networks:
      - spectrum-network
    restart: unless-stopped
    command: python -u main.py

networks:
  spectrum-network:
    external: true
