version: '3.8'

services:
  spectrum-prism:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prism
    volumes:
      - .:/app
    environment:
      - QUESTDB_HOST=questdb
      - TIINGO_API_KEY=${TIINGO_API_KEY}
    networks:
      - spectrum-network
    restart: unless-stopped
    command: python -u main.py

networks:
  spectrum-network:
    external: true
