name: data_inv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - requests
  - ipykernel
  - pip:
    - questdb
    - tiingo
    - websocket-client
    - python-binance
    - python-dotenv
